### ISSUE TITLE
checked.cache spam

### ISSUE THREAD

**Issue by daveyoi** [vqmod/vqmod#94]
Hey Guys,

Got an odd issue using 2.6.1 with opencart 2.2.

the checked.cache file is full of duplicate references to /vendor/autoload.php  - it is a pretty busy site with a lot of ajax so the number of requests is pretty high.. so after 6 days we have over half a million records in the checked.cache file -  which is causing massive slow down (due to the amount of array looping)

If we delete the checked.cache site performance comes back - but the file is again receiving a new /vendor/autoload line on every request.

Any ideas how to stop this?

**Comment by JAY6390** [comment]
Hi Dave. Interesting bug - haven't seen that but haven't really checked for it. Will take a look at that shortly and see what I can find if anything

**Comment by JAY6390** [comment]
Hi Dave. Tried this on a 2.2 and 2.3 install and I don't actually see any autoload at all in the checked.cache file. It's not a standard file. Can you show the content of your vendor directory

**Comment by daveyoi** [comment]
@JAY6390 - Thanks for the quick response!

The vendor directory is the one that is provided with the 2.2 compiled download from opencart.com with the addition of the bugsnag library.

The directory is outside of the public_html doc root

In the file the duplicates are all full path

```
/home/makemyvapeco/vendor/autoload.php
```
where as other entries are like this
```
system/engine/event.php
system/engine/model.php
system/engine/registry.php
system/engine/proxy.php
system/helper/general.php
system/helper/utf8.php
system/helper/json.php
system/helper/hash_equals.php
```
and only appear once.

There is one odd thing with this install,  in the config.php at the root declares its paths like this.

```php
define('DIR_APPLICATION', './catalog/');
define('DIR_SYSTEM', './system/');
define('DIR_IMAGE', './image/');
define('DIR_LANGUAGE', './catalog/language/');
define('DIR_TEMPLATE', './catalog/view/theme/');
define('DIR_CONFIG', './system/config/');
define('DIR_CACHE', './system/storage/cache/');
define('DIR_DOWNLOAD', './system/storage/download/');
define('DIR_LOGS', './system/storage/logs/');
define('DIR_MODIFICATION', './system/storage/modification/');
define('DIR_UPLOAD', './system/storage/upload/');
```
Should I change these to full paths maybe?

**Comment by JAY6390** [comment]
@daveyoi Yes I'd definitely change those to full paths. Those should always be full paths - I've seen partial paths like that cause issues in the past with third party applications. The issue with the autoload can probably be solved in a simpler manner, as VQMod won't actually modify any files outside the root of the site (or shouldn't!). Open your `/system/startup.php` file and find this line

```
require_once(DIR_SYSTEM . '../../vendor/autoload.php');
```

Change it to

```
require_once((DIR_SYSTEM . '../../vendor/autoload.php'));
```

That should stop vqmod applying to it, as it won't match. You may need to refresh your modifications in the opencart admin under `EXTENSIONS > MODIFICATIONS`

Kind regards
Jay

**Comment by daveyoi** [comment]
@JAY6390 Cheers mate..  but no go on that quick fix - vqmod still adds modCheck to that line.

Also correcting the paths in config.php didn't fix it - but i felt better for changing it to full paths :)

For now we have disabled our bugsnag module - and removed the vendor directory as it is not crucial to the running of the live site.

**Comment by JAY6390** [comment]
simply renaming the autoload.php file would probably been enough. Looks like just adding a space after the `require_once` would be enough to disable the vqmod modcheck applying to it. I forgot we made the modcheck a bit smarter in more recent versions to allow multiple braces

**Comment by pearlpandz** [comment]
guys any one help me...

i recently work with opencart 2.3.0.2. it show one error after hosting PHP 5.4+ required... but my boss need it to run 5.3 version.... what i do? please remember one thing php version 5.3 only


thank you

**Comment by JAY6390** [comment]
@pearlpandz Not a vqmod issue - use the opencart forums or hire a developer

**Comment by realseanwatson** [comment]
Hey @JAY6390 I am currently having the same issue, I deleted the check.cache and my Server RAM that was maxing out got reduced about 50% and I am no longer getting internal server errors. I recently installed VQMod. Adding space after require_once in that line will cause any issues?

**Comment by realseanwatson** [comment]
> Hey @JAY6390 I am currently having the same issue, I deleted the check.cache and my Server RAM that was maxing out got reduced about 50% and I am no longer getting internal server errors. I recently installed VQMod. Adding space after require_once in that line will cause any issues?

I also have other duplicate lines.

**Comment by AdrianOlmedo** [comment]
> Hey @JAY6390 I am currently having the same issue, I deleted the check.cache and my Server RAM that was maxing out got reduced about 50% and I am no longer getting internal server errors. I recently installed VQMod. Adding space after require_once in that line will cause any issues?

Try this https://github.com/vqmod/vqmod/pull/152/commits/3d77280075a5f8c8f5cee1c5f17e2caa1bca60bf

**Comment by AdrianOlmedo** [comment]
> > Hey @JAY6390 I am currently having the same issue, I deleted the check.cache and my Server RAM that was maxing out got reduced about 50% and I am no longer getting internal server errors. I recently installed VQMod. Adding space after require_once in that line will cause any issues?
> 
> I also have other duplicate lines.

Duplicate lines? Try this, it work for me https://github.com/vqmod/vqmod/pull/155/commits/8146fe96d315af8e50e8c8f1d5f5b738113aaae1

**Comment by realseanwatson** [comment]
> @realseanwatson
> 
> > > Hey @JAY6390 I am currently having the same issue, I deleted the check.cache and my Server RAM that was maxing out got reduced about 50% and I am no longer getting internal server errors. I recently installed VQMod. Adding space after require_once in that line will cause any issues?
> > 
> > 
> > I also have other duplicate lines.
> 
> Duplicate lines? Try this, it work for me [8146fe9](https://github.com/vqmod/vqmod/commit/8146fe96d315af8e50e8c8f1d5f5b738113aaae1)

Thank you, Adrian! This worked for me!
